language: ruby
rvm:
  - 2.3.0

notifications:
  slack:
      rooms:
            - oneandzeroweb:g0nMkPgQoz9TaYvhJjHDBLrh#general            
            - oneandzeroweb:g0nMkPgQoz9TaYvhJjHDBLrh#server-deployment
